<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
	'Administration' => 'YCM',
	'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
	'CSV' => 'CSV',
	'Changes saved.' => 'Изменения сохранены',
	'Changes saved. You can add a new entry.' => 'Изменения сохранены. Вы можете добавить новую запись.',
	'Choose {name}' => 'Choose {name}',
	'Could not create folder "{dir}". Make sure "uploads" folder is writable.' => 'Could not create folder "{dir}". Make sure "uploads" folder is writable.',
	'Could not create upload folder "{dir}".' => 'Could not create upload folder "{dir}".',
	'Could not delete entry "{name}" with an ID "{pk}".' => '',
	'Could not load model "{name}".' => '',
	'Could not save file or file exists: "{file}".' => '',
	'Could not upload file.' => '',
	'Create' => 'Создать',
	'Create {name}' => 'Создать {name}',
	'Delete' => 'Удалить',
	'Download' => 'Скачать',
	'Download {name}' => 'Скачать {name}',
	'Edit {name}' => 'Редактировать',
	'Error' => 'Ошибка',
	'Excel' => '',
	'Home' => 'Главная',
	'Image' => 'Изображение',
	'Image preview' => 'Миниатюра',
	'Incorrect username or password.' => 'Непрвильное имяпользователя либо пароль',
	'Invalid file extension "{ext}".' => 'Неправильное расширение файла "{ext}"',
	'List' => 'Список',
	'Login' => 'Войти',
	'Logout' => 'Выйти',
	'MS CSV' => '',
	'Password' => 'Пароль',
	'Please configure "username" and "password" properties of the module in configuration file.' => '',
	'Please enter your username and password.' => 'Введите имя пользователя и пароль',
	'Preview' => 'Превью',
	'Remember me next time' => 'Запомнить меня',
	'Save' => 'Сохранить',
	'Save and add another' => 'Сохранить и создать еще',
	'Save and continue editing'=> 'Сохранить и продолжать редактировать',
	'Username' => 'Имя пользователя',
);
